apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: example-applicationset
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - cluster: dev
            project: app1
          - cluster: qa
            cluster: dev
            cluster: prod
            project: app2
  template:
    metadata:
      name: '{{project}}-{{cluster}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/cgathefirst/gitops-argo.git
        targetRevision: application
        path: '{{project}}/k8s-{{cluster}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{project}}-{{cluster}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
