apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: example-applicationset
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - project: app1
            cluster: dev
          - project: app1
            cluster: qa
          - project: app1
            cluster: prod
          - project: app2
            cluster: dev
          - project: app2
            cluster: prod
          - project: app2
            cluster: qa




            
  template:
    metadata:
      name: '{{project}}-{{cluster}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/cgathefirst/gitops-argo.git
        targetRevision: second
        path: '{{project}}/k8s-{{cluster}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{project}}-{{cluster}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
      synOptions:
        - CreateNamespace=true
