apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: projects-qa-only
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - list:
        elements:
          - app: app1
            cluster: k8s-dev
            cluster: k8s-prod
            cluster: k8s-qa
          - app: app2
            cluster: k8s-dev
            cluster: k8s-prod
            cluster: k8s-qa
  template:
    metadata:
      name: '{{.app}}-{{.cluster}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/cgathefirst/gitops-argo.git
        targetRevision: second
        path: '{{.app}}/{{.cluster}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{.app}}-{{.cluster}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
