---
# Source: just-app/templates/service.yaml
kind: Service     
apiVersion: v1     
metadata:
  name: examgabieyal-qa-svc #from RELEASE NAME
spec:
  type: ClusterIP
  ports:
   - port: 8000  
     targetPort: 8000  
     name: http   
     protocol: TCP
  selector:
    app: examgabieyal-qa
---
# Source: just-app/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: examgabieyal-qa-deploy
spec:
  selector: 
    matchLabels:
      app: examgabieyal-qa
  replicas: 2   #from values
  template:
    metadata:
      labels:
        app: examgabieyal-qa
    spec:
      containers:
      - name: examgabieyal-qa #from values
        image: cgabya12/examgabieyal:qa #from values
        ports:
        - containerPort: 8000
---
# Source: just-app/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name:  examgabieyal-qa-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name:  examgabieyal-qa-svc
                port:
                  number: 8000
