---
# Source: just-app/templates/service.yaml
kind: Service     
apiVersion: v1     
metadata:
  name: examgabieyal-null-svc #from RELEASE NAME
spec:
  type: ClusterIP
  ports:
   - port: 8000  
     targetPort: 8000  
     name: http   
     protocol: TCP
  selector:
    app: examgabieyal-null
---
# Source: just-app/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: examgabieyal-null-deploy
spec:
  selector: 
    matchLabels:
      app: examgabieyal-null
  replicas: 1   #from values
  template:
    metadata:
      labels:
        app: examgabieyal-null
    spec:
      containers:
      - name: examgabieyal-null #from values
        image: cgabya12/examgabieyal:latest #from values
        ports:
        - containerPort: 8000
---
# Source: just-app/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name:  examgabieyal-null-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name:  examgabieyal-null-svc
                port:
                  number: 8000
